apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: job-3
  name: pod-logs-reader
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: podsloguser
  namespace: job-3
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: podlogsbings
  namespace: job-3
  labels:
    operator: rook
    storage-backend: ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-logs-reader
subjects:
- kind: ServiceAccount
  name: podsloguser
  namespace: job-3

